tripal.bio_data.*:
  type: config_entity
  label: 'Tripal Content Type'
  mapping:
    id:
      type: integer
      label: 'ID'
    name:
      type: string
      label: 'Name'
    label:
      type: label
      label: 'Label'
    term_id:
      type: integer
      label: 'Term ID'
    help_text:
      type: text
      label: 'Help Text'
    category:
      type: text
      label: 'Category'
    title_format:
      type: text
      label: 'Title Format'
    url_format:
      type: text
      label: 'URL Format'
    hide_empty_field:
      type: boolean
      label: 'Hide Empty Fields'
    ajax_field:
      type: boolean
      label: 'AJAX Field Loading'
