name: Build and Publish Docker image
on:
  push:
    branches:
      - autobuild-image
jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        drupalversion: ['9.0.x-dev', '9.1.x-dev', '9.2.x-dev']
    name: Docker Build (drupal${{ matrix.drupalversion }})
    steps:
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            tripalproject/tripaldocker:drupal${{ matrix.drupalversion }}-test
            ${{ (matrix.drupalversion == '9.1.x-dev' && 'tripalproject/tripaldocker:latest-test' ) || '' }}
          build-args: "drupalversion=${{ matrix.drupalversion }}"
