# Run some PHPUnit tests
name: Test Coverage

# When do we want the tests to run?
on: [push, pull_request]

# Define jobs that are part of the workflow
jobs:
  # Job 1: 'build'
  run-tests:
    # Runner type
    runs-on: ubuntu-latest
    name: Test Coverage

    steps:
      # Check out the repo
      - name: Checkout Repository
        uses: actions/checkout@v2
      # Just spin up docker the good ol' fashion way.
      - name: Spin up Docker
        run: |
          docker run --publish=80:80 --name=tripaldocker -tid \
            --volume=`pwd`:/var/www/drupal8/web/modules/contrib/tripal \
            tripalproject/tripaldocker:drupal8.9.x-dev
          docker exec tripaldocker service postgresql restart
          docker exec tripaldocker drush cr
          docker exec tripaldocker drush trp-drop-chado --schema-name=chado
          docker exec tripaldocker drush trp-prep-tests
      # Ensure we have the variables we need.
      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v3.x
      # Prepare for code coverage.
      - name: Prepare for Code Coverage
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
          docker cp cc-test-reporter tripaldocker:/var/www/drupal8/web/modules/contrib/tripal
          docker exec tripaldocker chmod a+x /var/www/drupal8/web/modules/contrib/tripal/cc-test-reporter
          docker exec --workdir=/var/www/drupal8/web/modules/contrib/tripal tripaldocker ./cc-test-reporter before-build --debug
      # Runs the PHPUnit tests.
      # https://github.com/mheap/phpunit-github-actions-printer is used
      # to report PHPUnit fails in a meaningful way to github in PRs.
      # Stopped using mheap due to warning w/ phpunit8->9
      - name: Run Tests for Coverage
        env:
          SIMPLETEST_BASE_URL: "http://localhost"
          SIMPLETEST_DB: "pgsql://drupaladmin:drupal8developmentonlylocal@localhost/sitedb"
          BROWSER_OUTPUT_DIRECTORY: "/var/www/drupal8/web/sites/default/files/simpletest"
        run: |
          docker exec tripaldocker service postgresql restart
          docker exec -e SIMPLETEST_BASE_URL=$SIMPLETEST_BASE_URL \
            -e SIMPLETEST_DB=$SIMPLETEST_DB \
            -e BROWSER_OUTPUT_DIRECTORY=$BROWSER_OUTPUT_DIRECTORY \
            --workdir=/var/www/drupal8/web/modules/contrib/tripal \
            tripaldocker phpunit --coverage-text --coverage-clover ./clover.xml
      - name: Publish code coverage to Code Climate
        run: |
          docker exec --workdir=/var/www/drupal8/web/modules/contrib/tripal \
            tripaldocker ./cc-test-reporter after-build clover.xml \
            --id 33d9655ce902af56f5f85c901a8ee79948aaa5b5c5db2814037202517bfe7b26 \
            --debug -t clover -p /var/www/drupal8/web/modules/contrib/tripal
