# Run some PHPUnit tests
name: PHPUnit-Tests

# When do we want the tests to run?
on: [push, pull_request]

# Define jobs that are part of the workflow
jobs:
  # Job 1: 'build'
  run-tests:
    # Runner type
    runs-on: ubuntu-latest
    # PHP Targets
    strategy:
      matrix:
        dockertags: ['drupal8.9.10-dev']
    # Give the builds names so we can tell them apart
    name: PHPUnit Testing (TipalDocker ${{ matrix.dockertags }})

    # Steps in the sequence
    steps:
      # Check out the repo
      - name: Checkout Repository
        uses: actions/checkout@v2
      # Just spin up docker the good ol' fashion way.
      - name: Spin up Docker
        run: |
          docker run --publish=80:80 --name=tripaldocker -tid \
            --volume=`pwd`:/var/www/drupal8/web/modules/t4d8 \
            tripalproject/tripaldocker:${{ matrix.dockertags }}
          docker exec -it tripaldocker drush status
      # Runs the PHPUnit tests.
      # https://github.com/mheap/phpunit-github-actions-printer is used
      # to report PHPUnit fails in a meaningful way to github in PRs.
      - name: PHPUnit Tests
        run: |
          docker exec -it tripaldocker pwd
          docker exec -it tripaldocker ls
          docker exec -it tripaldocker composer require --dev mheap/phpunit-github-actions-printer
          docker exec -it tripaldocker composer update
          docker exec -it tripaldocker phpunit --printer mheap\\GithubActionsReporter\\Printer --configuration web/core web/modules/t4d8
      
